'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const {spawn}=require('node:child_process');const Database=require('better-sqlite3'),bcrypt=require('bcryptjs');
const root=path.resolve(__dirname,'..');
test('HTTP pool auth, real/both/admin allocation, empty blocking and same-package rebuild',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mizan-pool-http-'));
 for(const name of ['server.js','utils','public'])fs.cpSync(path.join(root,name),path.join(dir,name),{recursive:true});
 fs.mkdirSync(path.join(dir,'database'));fs.copyFileSync(path.join(root,'database/db.js'),path.join(dir,'database/db.js'));
 fs.symlinkSync(path.join(root,'node_modules'),path.join(dir,'node_modules'),'dir');
 fs.writeFileSync(path.join(dir,'utils/apkbuilder.js'),"module.exports={makePackageName:()=> 'com.synthetic.fake',buildApk:async()=>({success:false,error:'Synthetic test failure; no compilation or network'})};");
 const port=35000+Math.floor(Math.random()*15000),base='http://127.0.0.1:'+port,password='synthetic-admin-password',token='123456:synthetic-token';
 const child=spawn(process.execPath,['server.js'],{cwd:dir,env:{...process.env,NODE_ENV:'development',HOST:'127.0.0.1',PORT:String(port),BASE_URL:base,ADMIN_ORIGIN:base,SESSION_SECRET:crypto.randomBytes(32).toString('hex'),CONTENT_ENCRYPTION_PASSWORD:crypto.randomBytes(32).toString('hex'),ADMIN_PASSWORD_HASH:bcrypt.hashSync(password,10),TELEGRAM_BOT_TOKEN:token,TELEGRAM_ALLOWED_IDS:'123',TELEGRAM_PACKAGE_ADMIN_IDS:'',TELEGRAM_APPROVER_IDS:'',TELEGRAM_ADMIN_CHAT_ID:'',BOT_POLLING_ENABLED:'false',FIREBASE_DATABASE_URL:'',FIREBASE_PROJECT_ID:'',GOOGLE_APPLICATION_CREDENTIALS:''},stdio:['ignore','pipe','pipe']});
 let log='',db;
 child.stderr.on('data',b=>log+=b);
 try{
  await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('Startup timeout '+log)),10000);child.once('exit',()=>{clearTimeout(t);reject(Error('Exited '+log));});child.stdout.on('data',b=>{if(String(b).includes('running on port')){clearTimeout(t);resolve();}});});
  db=new Database(path.join(dir,'database/mizanmod.db'));
  const req=(url,method='GET',body,cookie)=>fetch(base+url,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(cookie?{Cookie:cookie}:{})},body:body?JSON.stringify(body):undefined});
  const admin=await req('/api/admin/login','POST',{username:'admin',password}),cookie=admin.headers.get('set-cookie').split(';')[0];
  const params=new URLSearchParams({auth_date:String(Math.floor(Date.now()/1000)),user:JSON.stringify({id:123,first_name:'Test'})});const secret=crypto.createHmac('sha256','WebAppData').update(token).digest();params.set('hash',crypto.createHmac('sha256',secret).update([...params.keys()].sort().map(k=>k+'='+params.get(k)).join('\n')).digest('hex'));
  const auth=await req('/api/auth/telegram-webapp','POST',{initData:params.toString()}),client=auth.headers.get('set-cookie').split(';')[0];
  const user=db.prepare('SELECT * FROM users WHERE telegram_id=?').get('123');db.prepare('UPDATE users SET coins=100 WHERE id=?').run(user.id);
  fs.writeFileSync(path.join(dir,'templates/test.html'),'<html>Test</html>');
  const design=db.prepare("INSERT INTO designs(name,price_coins,popup_html_file) VALUES('Test',10,'test.html')").run().lastInsertRowid;
  assert.equal((await req('/api/admin/packages')).status,403);
  assert.equal((await req('/api/admin/packages','POST',{packages:'com.attacker.name'},client)).status,403);
  assert.equal((await req('/api/admin/packages/admins','POST',{ids:'*'},cookie)).status,400);
  assert.match(await (await req('/admin/')).text(),/\/admin\/package-pool.js/);
  const payload={design_id:design,app_name:'Test',register_url:'https://example.test/register'};
  let r=await req('/api/order','POST',payload,client);assert.equal(r.status,409);assert.equal((await r.json()).code,'PACKAGE_POOL_EMPTY');
  assert.equal(db.prepare('SELECT count(*) n FROM orders').get().n,0);assert.equal(db.prepare('SELECT coins FROM users').get().coins,100);
  assert.equal((await req('/api/admin/orders/create','POST',{...payload,user_id:user.id},cookie)).status,409);
  const added=await (await req('/api/admin/packages','POST',{packages:'📦 Allocated Packages:\n• com.mizan.a1\n• com.mizan.a2'},cookie)).json();assert.equal(added.added.length,2);
  const first=await (await req('/api/order','POST',payload,client)).json();assert.equal(first.success,true);
  const second=await (await req('/api/order','POST',{...payload,build_mode:'both',fake_register_url:'https://example.test/alternate'},client)).json();assert.equal(second.success,true);
  const wait=async id=>{for(let i=0;i<60;i++){if(db.prepare('SELECT status FROM orders WHERE id=?').get(id)?.status==='failed')return;await new Promise(r=>setTimeout(r,25));}throw Error('Expected synthetic failure');};
  await wait(first.orderId);await wait(second.orderId);
  assert.equal(db.prepare('SELECT package_name FROM orders WHERE id=?').get(first.orderId).package_name,'com.mizan.a1');
  assert.equal(db.prepare('SELECT package_name FROM orders WHERE id=?').get(second.orderId).package_name,'com.mizan.a2');
  assert.equal(db.prepare("SELECT count(*) n FROM package_pool WHERE state='reserved'").get().n,2);
  assert.equal(db.prepare('SELECT coins FROM users').get().coins,100);
  r=await req('/api/order','POST',payload,client);assert.equal(r.status,409);
  const fake=await (await req('/api/order','POST',{...payload,build_mode:'fake',fake_register_url:payload.register_url},client)).json();assert.equal(fake.success,true);await wait(fake.orderId);assert.equal(db.prepare('SELECT count(*) n FROM package_pool').get().n,2);
  const rebuild=await (await req('/api/admin/orders/'+first.orderId+'/rebuild','POST',{},cookie)).json();assert.ok(!rebuild.error,JSON.stringify(rebuild));await wait(first.orderId);assert.equal(db.prepare('SELECT package_name FROM orders WHERE id=?').get(first.orderId).package_name,'com.mizan.a1');
  await req('/api/admin/packages','POST',{packages:'com.mizan.admin'},cookie);
  const free=await (await req('/api/admin/orders/create','POST',{...payload,user_id:user.id},cookie)).json();assert.equal(free.success,true);await wait(free.orderId);
  assert.equal(db.prepare('SELECT package_name FROM orders WHERE id=?').get(free.orderId).package_name,'com.mizan.admin');
  assert.equal(db.prepare('SELECT coins FROM users').get().coins,100);
 }finally{db?.close();child.kill('SIGTERM');await new Promise(resolve=>child.exitCode!==null?resolve():child.once('exit',resolve));fs.rmSync(dir,{recursive:true,force:true});}
});
