plugins { id 'com.android.application' }
android {
    namespace 'com.mizanmods.shell'
    compileSdk 35
    buildToolsVersion '35.0.0'
    defaultConfig {
        applicationId '__PACKAGE__'
        minSdk 23
        targetSdk 35
        versionCode __VERSION_CODE__
        versionName '__VERSION_NAME__'
    }
    buildTypes {
        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
